### ISSUE TITLE
Definir cuestiones iniciales

### ISSUE THREAD

**Issue by Malows** [InforAlonso/f1212#1]
# Cosas que pienso que hay que definir
## Las cartas sobre la mesa
Python 3 de cabeza, me imagino
## Estructura
- De aplicaciones
- De modelos
    - Hay que analizar bien los requerimiento

## Dependencias
Además de Django, de seguro algo de JS se va a usar. Bower nos puede ayudar
Tenemos para elegir un monton, `bootstrap`, `angular`, `polymer`
## Gitignore
Ignora los tipos de las base de datos, pueden generarnos inconsistencias
Usamos base de datos local, no?
## Branching
Movemos dos ramas y vamos haciendo merging al master?

**Comment by hackerzeta** [comment]
python 3 y Django 1.8.5
 la estructura podria ser de aplicaciones, eso lo vamos a ver despues con mas tiempo, 
y las dependencias estaria muy bueno para poder manejar alertas
si, base de datos local, por eso subi una base en blanco de sqlite, ya que va a ser simplemente para trabajar en una maquina, aunque podriamos hacer una copia en la nube para evitar problemas por fallos en la maquina que se va a trabajar
y estaria bueno manejar dos ramas para evitar inconsistencias mientras que trabajemos en aplicaciones diferentes al mismo tiempo

**Comment by Malows** [comment]
Vamos por la 1.9 / 1.8.7, No se empaquetarlo, supongo que internet dara la respuesta
Podríamos ver las api de dropbox y todo eso
Alertas de que tipo? En local? En navegador o pc?

**Comment by hackerzeta** [comment]
Dale, entonces lo descargo al 1.9, y querían una alerta de tardanza de
taller
Ahi veo la api de dropbox

**Comment by Malows** [comment]
Copate, arma una organización(con nombre humano), migra el repo, agregame y dame owner a mi también, así no tengo que andar tirando pull request todo el tiempo
